# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'mail'
gem 'mechanize'
gem 'net-imap'
gem "functions_framework"
gem "google-cloud-secret_manager"
